# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
  #    providers:
  #        in_memory:
  #            memory: ~
    providers:
        in_memory:
            memory:
                users:
                    admin:
                       password: admin
                       roles: 'ROLE_USERS'
        main:
                entity: { class: AppBundle\Entity\User, property: username }
    encoders:
         Symfony\Component\Security\Core\User\User: plaintext
         AppBundle\Entity\User: sha512
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            #path: ^/
            anonymous: ~
            form_login:
                login_path:  /login
                check_path:  /login_check
            logout:
                path:   /logout
                target: /
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
    role_hierarchy:
        ROLE_ADMIN:       ROLE_SONATA_ADMIN

    access_control:
            - { path: ^/admin, roles: IS_AUTHENTICATED_ANONYMOUSLY }